export const NODE_ENV = process.env.REACT_APP_NODE_ENV;
export const DEV_BASE_URL = process.env.REACT_APP_DEV_BASE_URL;
export const PROD_BASE_URL = process.env.REACT_APP_PROD_BASE_URL;
export const LOGIN_URL = process.env.REACT_APP_LOGIN_URL;
export const REGISTER_URL = process.env.REACT_APP_REGISTER_URL;
export const GET_REG_STATUS_URL = process.env.REACT_APP_GET_REG_STATUS_URL;
export const CREATE_CATEGORY_URL = process.env.REACT_APP_CREATE_CATEGORY_URL;
export const FETCH_ALBUMS_URL = process.env.REACT_APP_FETCH_ALBUMS_URL;
export const FETCH_CATEGORIES_URL = process.env.REACT_APP_FETCH_CATEGORIES_URL;
export const DELETE_CATEGORY_URL = process.env.REACT_APP_DELETE_CATEGORY_URL;
export const UPDATE_CATEGORY_URL = process.env.REACT_APP_UPDATE_CATEGORY_URL;
export const FETCH_ALL_CATEGORIES_URL =
  process.env.REACT_APP_FETCH_ALL_CATEGORIES_URL;
export const UPLOAD_IMAGE_URL = process.env.REACT_APP_UPLOAD_IMAGE_URL;
export const FETCH_ALL_IMAGES_URL = process.env.REACT_APP_FETCH_ALL_IMAGES_URL;
export const DELETE_IMAGE_URL = process.env.REACT_APP_DELETE_IMAGE_URL;
export const UPLOAD_VIDEO_URL = process.env.REACT_APP_UPLOAD_VIDEO_URL;
export const FETCH_ALL_VIDEOS_URL = process.env.REACT_APP_FETCH_ALL_VIDEOS_URL;
export const DELETE_VIDEO_URL = process.env.REACT_APP_DELETE_VIDEO_URL;
export const UPDATE_VIDEO_URL = process.env.REACT_APP_UPDATE_VIDEO_URL;
export const CREATE_ALBUM_URL = process.env.REACT_APP_CREATE_ALBUM_URL;
export const DELETE_ALBUM_URL = process.env.REACT_APP_DELETE_ALBUM_URL;
export const UPDATE_ALBUM_URL = process.env.REACT_APP_UPDATE_ALBUM_URL;
export const FETCH_IMAGES_FOR_ALBUM_CATEGORY_URL =
  process.env.REACT_APP_FETCH_IMAGES_FOR_ALBUM_CATEGORY_URL;
export const DELETE_IMAGE_FOR_ALBUM_CATEGORY =
  process.env.REACT_APP_DELETE_IMAGE_FOR_ALBUM_CATEGORY;
export const SEND_EMAIL = process.env.REACT_APP_SEND_EMAIL;
export const FETCH_DIRECT_IMAGES_FOR_ALBUM =
  process.env.REACT_APP_FETCH_DIRECT_IMAGES_FOR_ALBUM;
